apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: nebulift-platform
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: object-storage
    app.kubernetes.io/part-of: nebulift
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: s3
      port: 9000
      targetPort: s3
      protocol: TCP
    - name: console
      port: 9001
      targetPort: console
      protocol: TCP
