apiVersion: v1
kind: Namespace
metadata:
  name: nebulift-dev
  labels:
    environment: development
    app.kubernetes.io/name: nebulift-dev
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
