apiVersion: v1
kind: Namespace
metadata:
  name: nebulift-training
  labels:
    app.kubernetes.io/name: nebulift-training
    app.kubernetes.io/managed-by: argocd
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nebulift-data
  labels:
    app.kubernetes.io/name: nebulift-data
    app.kubernetes.io/managed-by: argocd
    argocd.argoproj.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
