apiVersion: v1
kind: Namespace
metadata:
  name: nebulift-platform
  labels:
    app.kubernetes.io/name: nebulift-platform
    app.kubernetes.io/part-of: nebulift
    app.kubernetes.io/managed-by: argocd
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
