apiVersion: v1
kind: Namespace
metadata:
  name: nebulift-training
  labels:
    environment: production
    app.kubernetes.io/name: nebulift-training
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
